[package]
name = "time"
version = "0.2.0"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
exclude = [".github", ".editorconfig", "rustfmt.toml"]
repository = "https://github.com/time-rs/time"
keywords = []
categories = ["date-and-time"]
license = "MIT OR Apache-2.0"
# TODO Add GitHub Actions badge once rust-lang/crates.io#1838 is merged.

[features]
default = ["std", "deprecated", "unstable"]
deprecated = ["log"]
std = []
unstable = []

[dependencies]
log = { version = "0.4", optional = true }
serde = { version = "1", optional = true, default-features = false, features = ["derive", "alloc"] }
